'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default1
    
    '''<summary>
    '''btnCoachMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCoachMode As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRosterEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRosterEditor As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''AnchorUserProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnchorUserProfile As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''litCurrentUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCurrentUser As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''AnchorLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnchorLogout As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''AnchorBtnZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnchorBtnZone As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''AnchorBtnSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnchorBtnSchedule As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''AnchorBtnStats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnchorBtnStats As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''litAdminEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAdminEdit As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlParentMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlParentMain As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlAdminAddScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdminAddScore As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblThunder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblThunder As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtThunderScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtThunderScore As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblOpponent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpponent As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtOppName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOppName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblOpponentScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpponentScore As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtOpponentScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpponentScore As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddScore As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblScoreMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litScoreboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litScoreboard As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlAdminAddAnnouncement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdminAddAnnouncement As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtAnnounce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnnounce As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''btnAddAnnouncement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddAnnouncement As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblAnnounceMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnnounceMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litAnnouncement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAnnouncement As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSchedule As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlTournSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTournSchedule As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlStats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStats As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''litHittingStats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHittingStats As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litPitchingStats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPitchingStats As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlEditRoster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEditRoster As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''litRosterInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litRosterInfo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlUserProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUserProfile As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''litUserProfileTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litUserProfileTitle As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblPassConf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPassConf As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litPasswordError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPasswordError As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''txtOldPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOldPassword As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNewPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewPassword As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtConfirmPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConfirmPassword As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnChangePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChangePassword As Global.System.Web.UI.WebControls.Button
End Class
